spring:
  application:
    name: commit-wealth-service
  mongodb:
    uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin
    auto-index-creation: true

mongock:
  migration-scan-package:
    - be.commit_wealth.migrations

server:
  port: 8082